# Generated by Django 4.1.3 on 2024-07-17 00:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('greenhousebackend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('species', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='UserPlant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhousebackend.plant')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhousebackend.user')),
            ],
        ),
        migrations.CreateModel(
            name='PlantTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhousebackend.plant')),
                ('tag_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='greenhousebackend.tag')),
            ],
        ),
    ]
