# Generated by Django 4.1.3 on 2024-08-07 00:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('greenhousebackend', '0002_plant_tag_userplant_planttag_plant_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='planttag',
            old_name='plant_id',
            new_name='plant',
        ),
        migrations.RenameField(
            model_name='planttag',
            old_name='tag_id',
            new_name='tag',
        ),
    ]
