# Generated by Django 4.1.3 on 2024-07-20 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhousebackend', '0002_plant_tag_userplant_planttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='image_URL',
            field=models.URLField(blank=True, null=True),
        ),
    ]
