# Generated by Django 4.1.3 on 2024-08-07 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('greenhousebackend', '0003_rename_plant_id_planttag_plant_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plant',
            name='tags',
        ),
        migrations.AddField(
            model_name='plant',
            name='tags',
            field=models.ManyToManyField(related_name='plants', through='greenhousebackend.PlantTag', to='greenhousebackend.tag'),
        ),
    ]
